# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-15 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=45)),
                ('Lname', models.CharField(max_length=45)),
                ('Email', models.CharField(max_length=45)),
                ('Password', models.CharField(max_length=45)),
                ('CPass', models.CharField(max_length=45)),
            ],
        ),
    ]
