# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-16 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_remove_user_cpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=45)),
                ('Password', models.CharField(max_length=45)),
            ],
        ),
    ]
